version: '3.4'

services:
########################################################## venta.api ################################################################################
  venta.api:
    image: ${DOCKER_REGISTRY-}ventaapi
    #container_name: Microservices.Demo.Product.Api
    mem_limit: 256m
    mem_reservation: 128M
    cpus: 0.25
    deploy:
      replicas: 3
    environment:      
      - ASPNETCORE_URLS=http://::80
    ports:
      - "80"      
    build:
      context: .
      dockerfile: Venta.API/Dockerfile
    networks:
      - backend
    restart: on-failure
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge